### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bigezhang** [deepu105/generator-jhipster-entity-audit#7]
when i use "yo jhipster-entity-audit", it throw error like "events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.copyTemplate is not a function
    at null.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:126:24)
    at Array.forEach (native)
    at copyFiles (/usr/local/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:125:15)
    at module.exports.yeoman.generators.Base.extend.writing.writeBaseFiles (/usr/local/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:146:12)
    at /usr/local/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)"

------
jhipster version is 2.26.2

**Comment by deepu105** [comment]
It's because the module generator-jhipster-entity-audit requires JHipster v2.26.3 or v2.27.0, which is not out yet. You have 2 solutions :

wait
or
use the latest master branch of JHipster and `npm link` it(like all JHipster contributors)
